require 'net/http'
require 'uri'
require 'base64'
#require 'hmac/sha1'
#require 'hmac'
require 'kconv'
require 'yaml'
require 'ostruct'

require 'nokogiri'
require 'openssl'

require 'facets/kernel/__method__'
require 'facets/hash/merge'
require 'facets/hash/recursively'
require 'facets/hash/symbolize_keys'
require 'facets/kernel/constant'
require 'facets/string/methodize'
require 'facets/string/modulize'
require 'facets/blank'
require 'facets/to_hash'
require 'facets/file'

require 'google-storage/authorization'
require 'google-storage/mime-type'
require 'google-storage/base'
require 'google-storage/acl'
require 'google-storage/acl-owner'
require 'google-storage/acl-entry'
require 'google-storage/request-methods'
require 'google-storage/service'
require 'google-storage/bucket'
